#!/usr/bin/env bash
# script to install nginx and set up its configuration

# install nginx on server
sudo apt-get -y update
sudo apt-get -y install nginx

# configure nginx
#make directory for the example website
sudo mkdir -p /var/www/iakevdesign.tech/text
#add a file containing root text to direcory
sudo echo "Hello World!" | sudo tee /var/www/iakevdesign.tech/text/hello > /dev/null

#add a file to serve as an error file
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/iakevdesign.tech/text/error > /dev/null
# create current site configuration using virtual hosts (server blocks)
sudo touch /etc/nginx/sites-available/iakevdesign.tech
# add server configurations to above file 'example.com'
host_name=$(grep 127.0.0.1 /etc/hosts | cut -d " " -f 2- | cut -d " " -f 2)
sudo echo "# Virtual Host configuration for iakevdesign.tech
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
server {
       listen 80;
       listen [::]:80;

       server_name  iakevdesign.tech;

       add_header X-Served-By $host_name;

       root /var/www/iakevdesign.tech/text;
       index hello;

       # Everything is a 404
       location / {
       		try_files \$uri \$uri/ =404;
       }

       location /redirect_me {
       		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
       }

       error_page 404 /error;
       location = /error {
       		root /var/www/iakevdesign.tech/text;
        	internal;
       }
}" | sudo tee /etc/nginx/sites-available/iakevdesign.tech > /dev/null

# enable example.com by adding a symlnk to sites-enabled/
sudo ln -s /etc/nginx/sites-available/iakevdesign.tech /etc/nginx/sites-enabled/

# remove default file from sites-enabled/
sudo rm /etc/nginx/sites-enabled/default

# restart nginx to have the changes commited
sudo service nginx restart

var = $?
return $var
