#!/usr/bin/env bash
# Bash script to set up and configure HAproxy in server
## Install HAProxy
sudo apt-get -y update
sudo apt-get install -y haproxy=2.6.\*

## Configure HAProxy
sudo echo "#HAproxy server conf
frontend iakev

	 #set up proxy mode to level 4 tcp/ip
	 mode http

	 #Recieve all IP addresses to listen on port 80
	 bind *:80

	 #choosing default backend servers
	 option fowardfor
	 default_backend web_servers

backend web_servers
	mode http
	balance roundrobin
	server 82807-web-01 18.204.5.6:80 check
	server 82807-web-02 100.26.241.83:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
#restart Haproxy on changing configuration settings
sudo service haproxy restart
