#!/usr/bin/env bash
# Bash script to set up and configure HAproxy in server
## Install HAProxy
sudo apt -y update
sudo apt install -y haproxy

## Configure HAProxy
sudo echo "frontend 82807-lb-01
      	  	     bind *:80
       		     mode http
		     default_backend web_servers
backend web_servers
       	balance roundrobin
       	server 82807-web-01 18.204.5.6:80 check
       	server 82807-web-02 100.26.241.83:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
#restart Haproxy on changing configuration settings
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
