#!/usr/bin/env bash
# Script to create a backup of all database in server

sudo mysqldump --user "root" --password "$1" --all-databases | sudo tee backup.sql

archive_name=$(date '+%d-%m-%Y')
tar -czf "$archive_name".tar.gz backup.sql
