#!/usr/bin/env bash
# Script that creates a file with its PID and traps some kill signals
trap "sudo rm /var/run/myscript.pid" EXIT
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
pgrep -f 100-process_and_pid_file | sudo tee /var/run/myscript.pid > /dev/null
while true; do
    echo "To infinity and beyond"
    sleep 3;
done
