#!/usr/bin/env bash
# Script that filters ps output to display lines containn=ing bash word
# shellcheck disable=SC2009
ps -eo uname,pid,%cpu,%mem,vsz,rss,tname,stat,start_time,bsdtime,command f | grep "bash"